In [27]:
import pandas as pd

df_scratch = pd.read_pickle('scratch_classification.pkl')
df_pretrained = pd.read_pickle('pretrained_classification.pkl')

In [28]:
df_join = pd.merge(df_scratch, df_pretrained, on=['Token Mixer', 'Kernel Size'], suffixes=('_scratch', '_pretrained'))

In [34]:
df = pd.DataFrame()
for p in df_scratch.columns:
    df[p] = df_join[f'{p}_pretrained']/df_join[f'{p}_scratch']

df = df.loc[~df.index.get_level_values(0).str.startswith('ResNet'), df.columns.str.endswith('_auc')]
df_no_imgwoof = df.iloc[:, 1:]
df

                         ImageWoof_auc  PathMNIST_auc  DermaMNIST_auc  \
Token Mixer Kernel Size
pooling     3                 1.015798       0.983398        1.020376
            5                 1.013029       0.984896        1.031422
            7                 1.016564       0.991963        1.045821
conv        3                 1.020774       0.972544        1.052104
            5                 1.022453       0.979753        1.031282
            7                 1.040282       0.983210        1.059689
sep_conv    3                 1.011328       0.981332        1.014999
            5                 1.015300       0.981672        1.034301
            7                 1.052457       1.000204        1.038360
locAttn     3                 1.056709       1.004536        1.025708
            5                 1.060413       1.001645        1.059147
            7                 1.072332       0.995297        1.087373
fullAttn    -                 1.085650       0.999694        0.986048
identity    -                 1.027676       0.974887        1.098133

                         PneumoniaMNIST_auc  OrganSMNIST_auc
Token Mixer Kernel Size
pooling     3                      0.990828         0.991577
            5                      1.005187         1.025920
            7                      0.997860         1.005839
conv        3                      1.007274         1.001154
            5                      1.005506         1.014142
            7                      0.995466         1.006735
sep_conv    3                      1.002023         0.990037
            5                      1.005576         1.014346
            7                      0.998583         0.999788
locAttn     3                      1.006366         1.011189
            5                      1.015849         1.031702
            7                      0.995104         1.024448
fullAttn    -                      1.041504         0.982746
identity    -                      1.002833         0.994598

# Pool Size

In [30]:
df.groupby('Kernel Size').mean()

,ImageWoof_auc,PathMNIST_auc,DermaMNIST_auc,PneumoniaMNIST_auc,OrganSMNIST_auc
Kernel Size,,,,,
-,1.056663,0.987291,1.042090,1.022169,0.988672
3,1.026152,0.985453,1.028297,1.001623,0.998489
5,1.027799,0.986992,1.039038,1.008030,1.021528
7,1.045408,0.992669,1.057811,0.996753,1.009202

In [31]:
df.groupby('Kernel Size').mean().mean(1).sort_values(ascending=False)

Kernel Size
7    1.020369
-    1.019377
5    1.016677
3    1.008003
dtype: float64

In [35]:
df_no_imgwoof.groupby('Kernel Size').mean().mean(1).sort_values(ascending=False)

Kernel Size
7    1.014109
5    1.013897
-    1.010055
3    1.003465
dtype: float64

# Token Mixer

In [32]:
df.groupby('Token Mixer').mean()

,ImageWoof_auc,PathMNIST_auc,DermaMNIST_auc,PneumoniaMNIST_auc,OrganSMNIST_auc
Token Mixer,,,,,
conv,1.027836,0.978502,1.047692,1.002749,1.007344
fullAttn,1.085650,0.999694,0.986048,1.041504,0.982746
identity,1.027676,0.974887,1.098133,1.002833,0.994598
locAttn,1.063151,1.000493,1.057409,1.005773,1.022446
pooling,1.015130,0.986752,1.032540,0.997958,1.007779
sep_conv,1.026361,0.987736,1.029220,1.002061,1.001390

In [33]:
df.groupby('Token Mixer').mean().mean(1).sort_values(ascending=False)

Token Mixer
locAttn     1.029854
identity    1.019626
fullAttn    1.019128
conv        1.012825
sep_conv    1.009354
pooling     1.008032
dtype: float64

In [36]:
df_no_imgwoof.groupby('Token Mixer').mean().mean(1).sort_values(ascending=False)

Token Mixer
locAttn     1.021530
identity    1.017613
conv        1.009072
pooling     1.006257
sep_conv    1.005102
fullAttn    1.002498
dtype: float64